// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plutus.Entities;

#nullable disable

namespace Plutus.Entities.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260808225501_AddDeviceSyncSignals")]
    partial class AddDeviceSyncSignals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("Plutus.Entities.Models.AuthActionAPIMapping", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("AuthActionAPIMapping");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuthActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAbbr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RecMarkup")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.Property<Guid>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("CheckoutItemChange");
                });

            modelBuilder.Entity("Plutus.Entities.Models.DBAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllApplicable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoApply")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanUseWithOtherDiscounts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("RequiredNumOfItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsesPerTransaction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CatIdOne")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatIdTwo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("CatIdOne", "CatIdTwo");

                    b.ToTable("DiscountCats");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("DiscountItems");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Emp_AuthActions", b =>
                {
                    b.Property<int>("AuthAId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmpId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthAId", "EmpId");

                    b.HasIndex("EmpId");

                    b.ToTable("EmpAuthActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BinnedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExPrice")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StockUntracked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.HasIndex("CatId", "IdTwo");

                    b.HasIndex("TaxId", "IdTwo");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Note", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Charge")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCashBackable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChangeable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumCharge")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PayMethods");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod_Sale", b =>
                {
                    b.Property<int>("PayId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Change")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PayId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("PaySales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdLine2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Plutus.Entities.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AuthoriserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CheckoutItemChangeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleIdReturned")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthoriserId");

                    b.HasIndex("CheckoutItemChangeId")
                        .IsUnique();

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleIdReturned");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ParentId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TillId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExTax")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TillId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.SavedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavedTransactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Stock", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdThree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdOne", "IdTwo", "IdThree");

                    b.HasIndex("IdThree");

                    b.HasIndex("IdOne", "IdTwo")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdLine2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashFloat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckoutItemChangeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemCostExPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemCostPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TillId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("CheckoutItemChangeId")
                        .IsUnique();

                    b.HasIndex("IdTwo");

                    b.HasIndex("TillId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction_Discount", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId", "DiscountId", "SaleId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("TransactionId", "SaleId");

                    b.ToTable("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.HasBaseType("Plutus.Entities.Models.Person");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractedHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManagedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Wage")
                        .HasColumnType("TEXT");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("StoreId");

                    b.HasIndex("Id", "BusinessId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActionAPIMapping", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Role", "Role")
                        .WithMany("AuthActionAPIMappings")
                        .HasForeignKey("IdOne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.AuthActions", "AuthAction")
                        .WithMany("AuthActionAPIMappings")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Categories")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("CheckoutItemChanges")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Discounts")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Category", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("DisCategoryList")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Category", "Cat")
                        .WithMany("Discount_Categories")
                        .HasForeignKey("CatIdOne", "CatIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Item", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("DisItemList")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("DisItems")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Emp_AuthActions", b =>
                {
                    b.HasOne("Plutus.Entities.Models.AuthActions", "AuthA")
                        .WithMany("EmpAuths")
                        .HasForeignKey("AuthAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Employee", "Emp")
                        .WithMany("EmpAuths")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthA");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Items")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Category", "Cat")
                        .WithMany("Items")
                        .HasForeignKey("CatId", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Tax", "Tax")
                        .WithMany("Items")
                        .HasForeignKey("TaxId", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Cat");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Note", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Notes")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod_Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.PaymentMethod", "PayMethod")
                        .WithMany("PaySales")
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("PaySales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayMethod");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Refund", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Employee", "Authoriser")
                        .WithMany("RefundsAuthorised")
                        .HasForeignKey("AuthoriserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.CheckoutItemChange", "CheckoutItemChange")
                        .WithOne("Refund")
                        .HasForeignKey("Plutus.Entities.Models.Refund", "CheckoutItemChangeId");

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Refunds")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Sale", "SaleReturned")
                        .WithMany("Refunded")
                        .HasForeignKey("SaleIdReturned")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("Refunds")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authoriser");

                    b.Navigation("CheckoutItemChange");

                    b.Navigation("Item");

                    b.Navigation("Sale");

                    b.Navigation("SaleReturned");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Roles")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Role", "ParentRole")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Business");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Employee", "Employee")
                        .WithMany("Sale")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Till", "Till")
                        .WithMany()
                        .HasForeignKey("TillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Store");

                    b.Navigation("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Stock", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Stocks")
                        .HasForeignKey("IdThree")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithOne("Stock")
                        .HasForeignKey("Plutus.Entities.Models.Stock", "IdOne", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Stores")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Taxes")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Tills")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.HasOne("Plutus.Entities.Models.CheckoutItemChange", "CheckoutItemChange")
                        .WithOne("Transaction")
                        .HasForeignKey("Plutus.Entities.Models.Transaction", "CheckoutItemChangeId");

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Transactions")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Till", "Till")
                        .WithMany("Transactions")
                        .HasForeignKey("TillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckoutItemChange");

                    b.Navigation("Item");

                    b.Navigation("Sale");

                    b.Navigation("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction_Discount", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("Transaction_Discounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Transaction", "Transaction")
                        .WithMany("Transaction_Discounts")
                        .HasForeignKey("TransactionId", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Employees")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Plutus.Entities.Models.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Employee", "ManagedBy")
                        .WithMany()
                        .HasForeignKey("ManagedById");

                    b.HasOne("Plutus.Entities.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId");

                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("ManagedBy");

                    b.Navigation("Role");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActions", b =>
                {
                    b.Navigation("AuthActionAPIMappings");

                    b.Navigation("EmpAuths");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Business", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Discounts");

                    b.Navigation("Employees");

                    b.Navigation("Items");

                    b.Navigation("Roles");

                    b.Navigation("Stores");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.Navigation("Discount_Categories");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.Navigation("Refund")
                        .IsRequired();

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.Navigation("DisCategoryList");

                    b.Navigation("DisItemList");

                    b.Navigation("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.Navigation("CheckoutItemChanges");

                    b.Navigation("DisItems");

                    b.Navigation("Refunds");

                    b.Navigation("Stock");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod", b =>
                {
                    b.Navigation("PaySales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.Navigation("AuthActionAPIMappings");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PaySales");

                    b.Navigation("Refunded");

                    b.Navigation("Refunds");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Sales");

                    b.Navigation("Stocks");

                    b.Navigation("Tills");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.Navigation("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.Navigation("EmpAuths");

                    b.Navigation("RefundsAuthorised");

                    b.Navigation("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
