<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net10.0-windows10.0.19041</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>Plutus.Frontend.ClientUI</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>Plutus</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.MBHConsulting.PlutusFrontendClientUI</ApplicationId>
		<ApplicationIdGuid>24649D73-0BD0-44A3-A5C3-0DD2FF5A3F76</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.18362.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.18362.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<DefaultLanguage>en</DefaultLanguage>
		<Title>Plutus Frontend ClientUI</Title>
		<Product>Plutus</Product>
		<Authors>Sean Knox</Authors>
		<Company>MBH.Consulting</Company>
		<RepositoryType>git</RepositoryType>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<PackageCertificateKeyFile>Plutus.Frontend.ClientUI_TemporaryKey.pfx</PackageCertificateKeyFile>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
	</PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.Contains('-windows')) and '$(Configuration)' == 'Release'">
    <GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
    <AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>042a5c82dd8e6b11ef24d614b8a4d20face8c073</PackageCertificateThumbprint>
  </PropertyGroup>
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Core\CustomViews\**" />
	  <AndroidResource Remove="Platforms\iOS\Core\CustomViews\**" />
	  <AndroidResource Remove="Platforms\MacCatalyst\Core\CustomViews\**" />
	  <AndroidResource Remove="Platforms\Windows\Core\CustomViews\**" />
	  <Compile Remove="Platforms\Android\Core\CustomViews\**" />
	  <Compile Remove="Platforms\iOS\Core\CustomViews\**" />
	  <Compile Remove="Platforms\MacCatalyst\Core\CustomViews\**" />
	  <Compile Remove="Platforms\Windows\Core\CustomViews\**" />
	  <EmbeddedResource Remove="Platforms\Android\Core\CustomViews\**" />
	  <EmbeddedResource Remove="Platforms\iOS\Core\CustomViews\**" />
	  <EmbeddedResource Remove="Platforms\MacCatalyst\Core\CustomViews\**" />
	  <EmbeddedResource Remove="Platforms\Windows\Core\CustomViews\**" />
	  <MauiCss Remove="Platforms\Android\Core\CustomViews\**" />
	  <MauiCss Remove="Platforms\iOS\Core\CustomViews\**" />
	  <MauiCss Remove="Platforms\MacCatalyst\Core\CustomViews\**" />
	  <MauiCss Remove="Platforms\Windows\Core\CustomViews\**" />
	  <MauiXaml Remove="Platforms\Android\Core\CustomViews\**" />
	  <MauiXaml Remove="Platforms\iOS\Core\CustomViews\**" />
	  <MauiXaml Remove="Platforms\MacCatalyst\Core\CustomViews\**" />
	  <MauiXaml Remove="Platforms\Windows\Core\CustomViews\**" />
	  <None Remove="Platforms\Android\Core\CustomViews\**" />
	  <None Remove="Platforms\iOS\Core\CustomViews\**" />
	  <None Remove="Platforms\MacCatalyst\Core\CustomViews\**" />
	  <None Remove="Platforms\Windows\Core\CustomViews\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="XAML\Controls\SteppedSliderWithLabels.xaml.cs" />
	</ItemGroup>
  
	<ItemGroup>
	  <MauiXaml Remove="XAML\Controls\SteppedSliderWithLabels.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Configuration\appsettings.dev.Android.json" />
	  <None Remove="Configuration\appsettings.dev.iOS.json" />
	  <None Remove="Resources\appicon.svg" />
	  <None Remove="Resources\appiconfg.svg" />
	  <None Remove="Resources\AppIcon\appicon.svg" />
	  <None Remove="Resources\Images\dotnet_bot.svg" />
	  <None Remove="Resources\Splash\splash.svg" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="Configuration\appsettings.dev.Android.json" />
	  <EmbeddedResource Include="Configuration\appsettings.dev.iOS.json" />
	  <EmbeddedResource Include="Configuration\appsettings.dev.json" />
	  <EmbeddedResource Include="Configuration\appsettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Mapster" Version="10.0.11" />
	  <PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
	  <PackageReference Include="CommunityToolkit.Maui.Markup" Version="7.0.0" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
	  <PackageReference Include="Microsoft.AppCenter" Version="5.0.1" />
	  <PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.1" />
	  <PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.1" />
	  <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="7.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Identity.Client" Version="4.61.3" />
	  <PackageReference Include="Syncfusion.Maui.ListView" Version="20.4.43" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Commons\CommonPOSLibrary\CommonPOSLibrary.csproj" />
	  <ProjectReference Include="..\..\Commons\CoppperToCSV\CoppperToCSV.csproj" />
	  <ProjectReference Include="..\..\Commons\Plutus.Repository\Plutus.Repository.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\I18N_L10N\Strings.resx" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Pages\MainTill\Inventory\AddEditInventoryItemPage.xaml.cs">
	    <DependentUpon>AddEditInventoryItemPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\MainTill\Inventory\ViewAllInventoryPage.xaml.cs">
	    <DependentUpon>ViewAllInventoryPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\MainTill\TillPage.xaml.cs">
	    <DependentUpon>TillPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\PopupViews\AdjustItemPage.xaml.cs">
	    <DependentUpon>AdjustItemPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\I18N_L10N\Strings.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Strings.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\I18N_L10N\Strings.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Strings.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Pages\MainTill\Inventory\AddEditInventoryItemPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MainTill\Inventory\InventoryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MainTill\Statistics\SalesReportPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MainTill\Statistics\StatisticsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MainTill\Statistics\StockOuttakePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\PopupViews\AdjustItemPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\PopupViews\AlterationPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\PopupViews\CategoryCreatePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\PopupViews\MoniesInputPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\PopupViews\ReturnItemPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\FontIcons.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="TestToolBarItem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\Android\Core\" />
	  <Folder Include="Platforms\iOS\Core\" />
	  <Folder Include="Platforms\MacCatalyst\Core\" />
	  <Folder Include="Platforms\Windows\Core\" />
	</ItemGroup>

</Project>
