<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableMauiImageProcessing>false</EnableMauiImageProcessing>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.17" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plutus.Frontend.AppClient\Plutus.Frontend.AppClient.csproj" />
    <ProjectReference Include="..\..\Data\Database\Database.csproj" />
    <ProjectReference Include="..\..\Shared\CommonPOSLibrary\CommonPOSLibrary.csproj" />
    <ProjectReference Include="..\..\Shared\CustomViews\CustomViews.csproj" />
    <ProjectReference Include="..\..\Shared\I18N_L10N\I18N_L10N.csproj" />
  </ItemGroup>

</Project>
