<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20181019194756_InitCreate.cs" />
    <Compile Remove="Migrations\20181021160046_InitCreate.cs" />
    <Compile Remove="Migrations\20181021163630_InitCreate.cs" />
    <Compile Remove="Migrations\20190612004639_PermmisionsRework.cs" />
    <Compile Remove="Migrations\20190612004639_PermmisionsRework.Designer.cs" />
    <Compile Remove="Migrations\20190805090540_NotifyPropertyChanged.cs" />
    <Compile Remove="Migrations\20190805090540_NotifyPropertyChanged.Designer.cs" />
    <Compile Remove="Migrations\20190805091004_NotifyPropertyChanged.cs" />
    <Compile Remove="Migrations\20190805091004_NotifyPropertyChanged.Designer.cs" />
    <Compile Remove="Migrations\20190805131027_NotifyPropertyChanged.cs" />
    <Compile Remove="Migrations\20190805131027_NotifyPropertyChanged.Designer.cs" />
    <Compile Remove="Migrations\20190805131136_NotifyPropertyChanged.cs" />
    <Compile Remove="Migrations\20190805131136_NotifyPropertyChanged.Designer.cs" />
    <Compile Remove="Migrations\20190829150337_SavedTransactionsRedesign.cs" />
    <Compile Remove="Migrations\20190829150337_SavedTransactionsRedesign.Designer.cs" />
    <Compile Remove="Migrations\20200224195601_ReworkAudit.cs" />
    <Compile Remove="Migrations\20200224195601_ReworkAudit.Designer.cs" />
    <Compile Remove="Migrations\20200412121719_DiscountAmountRecording_RefundTransactionDuplicationFix.cs" />
    <Compile Remove="Migrations\20200412121719_DiscountAmountRecording_RefundTransactionDuplicationFix.Designer.cs" />
    <Compile Remove="Migrations\20200412133717_DiscountAmountRecording.cs" />
    <Compile Remove="Migrations\20200412133717_DiscountAmountRecording.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.4" />
  </ItemGroup>
</Project>
