<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <UserSecretsId>3dc73556-626d-45a0-a0a6-0458a9b5f62c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <NoWin32Manifest>true</NoWin32Manifest>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="Tests\**" />
    <Content Remove="NewFolder1\**" />
    <Content Remove="Tests\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\ATestController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="6.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.24.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.15.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.1" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="6.14.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Commons\Plutus.Authentication\Plutus.Authentication.csproj" />
    <ProjectReference Include="..\..\Commons\Plutus.Reports\Plutus.Reports.csproj" />
    <ProjectReference Include="..\..\Commons\Plutus.Repository\Plutus.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
