using Plutus.Entities.Attributes;
using Plutus.Entities.Models.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Plutus.Entities.Models
{ 
    /// <summary>
    /// Transaction model, <typeparamref name="T1"></typeparamref> is an autogenerated integer and <typeparamref name="T2"></typeparamref> is a Sale ID 
    /// </summary>
    [Serializable]
    public class Transaction : CompositeBase<int, Guid>, ITransaction
    {
        #region Properties

        [Exportable]
        public int Amount { get; set; }

        [Exportable]
        public decimal ItemCostExPrice { get; set; }

        [Exportable]
        public decimal ItemCostPrice { get; set; }

        #region Relationships

        [Exportable]
        public string ItemIdOne { get; set; }
        [Exportable]
        public Guid ItemIdTwo { get; set; }
        public Item Item { get; set; }

        [Exportable]
        [Required]
        public Guid TillId { get; set; }
        public Till Till { get; set; }

        [Exportable]
        [Required]
        public Sale Sale { get; set; }

        [Exportable]
        public int? CheckoutItemChangeId { get; set; }
        public virtual CheckoutItemChange CheckoutItemChange { get; set; }

        #region Collections
        public virtual ICollection<Transaction_Discount> Transaction_Discounts { get; set; }
        #endregion
        #endregion
        #endregion
    }
}
