// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plutus.Entities;

namespace Plutus.Entities.Migrations.MySqlMigrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20211005142719_AddObjectIdEmployee")]
    partial class AddObjectIdEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Plutus.Entities.Models.AuthActionAPIMapping", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .HasColumnType("longtext");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("AuthActionAPIMapping");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuthActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Bussiness", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameAbbr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("RecMarkup")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("VatIN")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bussiness");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ExPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ItemIdOne")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemIdTwo")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("CheckoutItemChange");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllApplicable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("AutoApply")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BussinessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("CanUseWithOtherDiscounts")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("RequiredNumOfItems")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UsesPerTransaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BussinessId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("DiscountId");

                    b.ToTable("DiscountCats");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemIdOne")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemIdTwo")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("DiscountItems");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Emp_AuthActions", b =>
                {
                    b.Property<int>("AuthAId")
                        .HasColumnType("int");

                    b.Property<string>("EmpId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.HasKey("AuthAId", "EmpId");

                    b.HasIndex("EmpId");

                    b.ToTable("EmpAuthActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AdLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AdLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("BussinessId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<int>("ContractedHours")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("NIN")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParentUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Salt")
                        .HasColumnType("longtext");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("BussinessId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParentUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StoreId");

                    b.HasIndex("ObjectId", "BussinessId", "Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ExPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("CatId");

                    b.HasIndex("IdTwo");

                    b.HasIndex("TaxId", "IdTwo");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Notes_Sale", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<string>("SaleId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("NoteId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("NotesSales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCashBackable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsChangeable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MinimumCharge")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PayMethods");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod_Sale", b =>
                {
                    b.Property<int>("PayId")
                        .HasColumnType("int");

                    b.Property<string>("SaleId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("PayId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("PaySales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("AuthoriserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CheckoutItemChangeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemIdOne")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemIdTwo")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("SaleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SaleIdReturned")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuthoriserId");

                    b.HasIndex("CheckoutItemChangeId")
                        .IsUnique();

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleIdReturned");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ParentRoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("StoreId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalExTax")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.SavedTransaction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SavedTransactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Stock", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdThree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdOne", "IdTwo", "IdThree");

                    b.HasIndex("IdThree");

                    b.HasIndex("IdOne", "IdTwo")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AdLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("BussinessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("FullAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BussinessId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.Property<Guid>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("CashFloat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CheckoutItemChangeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemIdOne")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ItemIdTwo")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ItemsCostExPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ItemsCostPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("SaleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TillId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutItemChangeId")
                        .IsUnique();

                    b.HasIndex("SaleId");

                    b.HasIndex("TillId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction_Discount", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("TransactionId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActionAPIMapping", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Role", "Role")
                        .WithMany("AuthActionAPIMappings")
                        .HasForeignKey("IdOne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.AuthActions", "AuthAction")
                        .WithMany("AuthActionAPIMappings")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("CheckoutItemChanges")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Bussiness", "Bussiness")
                        .WithMany("Discounts")
                        .HasForeignKey("BussinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bussiness");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Category", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Category", "Cat")
                        .WithMany("DisCats")
                        .HasForeignKey("CatId");

                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("DisCategoryList")
                        .HasForeignKey("DiscountId");

                    b.Navigation("Cat");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Item", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("DisItemList")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("DisItems")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo");

                    b.Navigation("Discount");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Emp_AuthActions", b =>
                {
                    b.HasOne("Plutus.Entities.Models.AuthActions", "AuthA")
                        .WithMany("EmpAuths")
                        .HasForeignKey("AuthAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Employee", "Emp")
                        .WithMany("EmpAuths")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthA");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Bussiness", "Bussiness")
                        .WithMany("Employees")
                        .HasForeignKey("BussinessId");

                    b.HasOne("Plutus.Entities.Models.Employee", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId");

                    b.HasOne("Plutus.Entities.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId");

                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bussiness");

                    b.Navigation("ParentUser");

                    b.Navigation("Role");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Category", "Cat")
                        .WithMany("Items")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Bussiness", "Bussiness")
                        .WithMany("Items")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Tax", "Tax")
                        .WithMany("Items")
                        .HasForeignKey("TaxId", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bussiness");

                    b.Navigation("Cat");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Notes_Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Note", "Note")
                        .WithMany("NoteSales")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Notes")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod_Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.PaymentMethod", "PayMethod")
                        .WithMany("PaySales")
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("PaySales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayMethod");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Refund", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Employee", "Authoriser")
                        .WithMany("RefundsAuthorised")
                        .HasForeignKey("AuthoriserId");

                    b.HasOne("Plutus.Entities.Models.CheckoutItemChange", "CheckoutItemChange")
                        .WithOne("Refund")
                        .HasForeignKey("Plutus.Entities.Models.Refund", "CheckoutItemChangeId");

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Refunds")
                        .HasForeignKey("SaleId");

                    b.HasOne("Plutus.Entities.Models.Sale", "SaleReturned")
                        .WithMany("Refunded")
                        .HasForeignKey("SaleIdReturned");

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("Refunds")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo");

                    b.Navigation("Authoriser");

                    b.Navigation("CheckoutItemChange");

                    b.Navigation("Item");

                    b.Navigation("Sale");

                    b.Navigation("SaleReturned");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Role", "ParentRole")
                        .WithMany()
                        .HasForeignKey("ParentRoleId");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Employee", "Employee")
                        .WithMany("Sale")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId");

                    b.Navigation("Employee");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Stock", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Stocks")
                        .HasForeignKey("IdThree")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithOne("Stock")
                        .HasForeignKey("Plutus.Entities.Models.Stock", "IdOne", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Bussiness", "Bussiness")
                        .WithMany("Stores")
                        .HasForeignKey("BussinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bussiness");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Bussiness", "Bussiness")
                        .WithMany("Taxes")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bussiness");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Tills")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.HasOne("Plutus.Entities.Models.CheckoutItemChange", "CheckoutItemChange")
                        .WithOne("Transaction")
                        .HasForeignKey("Plutus.Entities.Models.Transaction", "CheckoutItemChangeId");

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Transactions")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Till", "Till")
                        .WithMany("Transactions")
                        .HasForeignKey("TillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo");

                    b.Navigation("CheckoutItemChange");

                    b.Navigation("Item");

                    b.Navigation("Sale");

                    b.Navigation("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction_Discount", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("Transaction_Discounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Transaction", "Transaction")
                        .WithMany("Transaction_Discounts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActions", b =>
                {
                    b.Navigation("AuthActionAPIMappings");

                    b.Navigation("EmpAuths");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Bussiness", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Employees");

                    b.Navigation("Items");

                    b.Navigation("Stores");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.Navigation("DisCats");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.Navigation("Refund");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.Navigation("DisCategoryList");

                    b.Navigation("DisItemList");

                    b.Navigation("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.Navigation("EmpAuths");

                    b.Navigation("RefundsAuthorised");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.Navigation("CheckoutItemChanges");

                    b.Navigation("DisItems");

                    b.Navigation("Refunds");

                    b.Navigation("Stock");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Note", b =>
                {
                    b.Navigation("NoteSales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod", b =>
                {
                    b.Navigation("PaySales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.Navigation("AuthActionAPIMappings");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PaySales");

                    b.Navigation("Refunded");

                    b.Navigation("Refunds");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Sales");

                    b.Navigation("Stocks");

                    b.Navigation("Tills");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.Navigation("Transaction_Discounts");
                });
#pragma warning restore 612, 618
        }
    }
}
