// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Database.Models.AuthActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AuthActions");
                });

            modelBuilder.Entity("Database.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Database.Models.Discount_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CatId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<int?>("DiscountId");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("StartDateTime");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("DiscountId");

                    b.ToTable("DiscountCats");
                });

            modelBuilder.Entity("Database.Models.Discount_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<int?>("DiscountId");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<string>("ItemId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("StartDateTime");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ItemId");

                    b.ToTable("DiscountItems");
                });

            modelBuilder.Entity("Database.Models.DiscountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.Property<int>("RequiredNumOfItems");

                    b.Property<int>("Type");

                    b.Property<int>("UsesPerTransaction");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Database.Models.Emp_AuthActions", b =>
                {
                    b.Property<int>("AuthAId");

                    b.Property<string>("EmpId");

                    b.Property<bool>("A");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("M");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<bool>("R");

                    b.Property<bool>("V");

                    b.Property<bool>("X");

                    b.HasKey("AuthAId", "EmpId");

                    b.HasIndex("EmpId");

                    b.ToTable("EmpAuthActions");
                });

            modelBuilder.Entity("Database.Models.EmployeeModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("AdLine1");

                    b.Property<string>("AdLine2");

                    b.Property<string>("City");

                    b.Property<int>("ContractedHours");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FName");

                    b.Property<string>("FullAddress");

                    b.Property<string>("HashedPassword");

                    b.Property<string>("LName");

                    b.Property<string>("Mobile");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("NIN");

                    b.Property<string>("PostCode");

                    b.Property<string>("Salt");

                    b.Property<string>("StoreId");

                    b.Property<decimal>("Wage");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Database.Models.ItemModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<int>("CatId");

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Desc");

                    b.Property<decimal>("ExPrice");

                    b.Property<byte[]>("Image");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("VatId");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("VatId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Database.Models.NoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Note");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Database.Models.Notes_SaleModel", b =>
                {
                    b.Property<int>("NoteId");

                    b.Property<string>("SaleId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.HasKey("NoteId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("NotesSales");
                });

            modelBuilder.Entity("Database.Models.PaymentMethod_SaleModel", b =>
                {
                    b.Property<int>("PayId");

                    b.Property<string>("SaleId");

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("Change");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.HasKey("PayId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("PaySales");
                });

            modelBuilder.Entity("Database.Models.PaymentMethodModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Charge");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsCashBackable");

                    b.Property<bool>("IsChangeable");

                    b.Property<decimal>("MinimumCharge");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PayMethods");
                });

            modelBuilder.Entity("Database.Models.RefundModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("ItemId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Reason");

                    b.Property<string>("SaleId");

                    b.Property<string>("SaleIdReturned");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleIdReturned");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Database.Models.SaleModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("DateOfSale")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmployeeId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<decimal>("Total");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Database.Models.SavedItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("ItemId");

                    b.Property<int>("SavedTransId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SavedTransId");

                    b.ToTable("SavedItems");
                });

            modelBuilder.Entity("Database.Models.SavedTransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SavedTransactions");
                });

            modelBuilder.Entity("Database.Models.StockModel", b =>
                {
                    b.Property<string>("ItemId");

                    b.Property<string>("StoreId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("Quantity");

                    b.HasKey("ItemId", "StoreId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Database.Models.StoreModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdLine1");

                    b.Property<string>("AdLine2");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("FullAddress");

                    b.Property<byte[]>("Logo");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("PostCode");

                    b.Property<decimal?>("RecMarkup");

                    b.Property<string>("StoreAbbr");

                    b.Property<string>("StoreName");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Database.Models.TaxModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<double>("Rate");

                    b.HasKey("Id");

                    b.ToTable("Vats");
                });

            modelBuilder.Entity("Database.Models.TransactionModel", b =>
                {
                    b.Property<string>("SaleId");

                    b.Property<string>("ItemId");

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.HasKey("SaleId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("Database.Models.Discount_Category", b =>
                {
                    b.HasOne("Database.Models.CategoryModel", "Cat")
                        .WithMany("DisCats")
                        .HasForeignKey("CatId");

                    b.HasOne("Database.Models.DiscountModel", "Discount")
                        .WithMany("DisCategoryList")
                        .HasForeignKey("DiscountId");
                });

            modelBuilder.Entity("Database.Models.Discount_Item", b =>
                {
                    b.HasOne("Database.Models.DiscountModel", "Discount")
                        .WithMany("DisItemList")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Database.Models.ItemModel", "Item")
                        .WithMany("DisItems")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("Database.Models.Emp_AuthActions", b =>
                {
                    b.HasOne("Database.Models.AuthActions", "Auth")
                        .WithMany("EmpAuths")
                        .HasForeignKey("AuthAId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.EmployeeModel", "Emp")
                        .WithMany("EmpAuths")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.EmployeeModel", b =>
                {
                    b.HasOne("Database.Models.StoreModel", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("Database.Models.ItemModel", b =>
                {
                    b.HasOne("Database.Models.CategoryModel", "Cat")
                        .WithMany("Items")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.TaxModel", "Vat")
                        .WithMany("Items")
                        .HasForeignKey("VatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.Notes_SaleModel", b =>
                {
                    b.HasOne("Database.Models.NoteModel", "Note")
                        .WithMany("NoteSales")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.SaleModel", "Sale")
                        .WithMany("Notes")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.PaymentMethod_SaleModel", b =>
                {
                    b.HasOne("Database.Models.PaymentMethodModel", "PayMethod")
                        .WithMany("PaySales")
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.SaleModel", "Sale")
                        .WithMany("PaySales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.RefundModel", b =>
                {
                    b.HasOne("Database.Models.ItemModel", "Item")
                        .WithMany("Refunds")
                        .HasForeignKey("ItemId");

                    b.HasOne("Database.Models.SaleModel", "Sale")
                        .WithMany("Refunds")
                        .HasForeignKey("SaleId");

                    b.HasOne("Database.Models.SaleModel", "SaleReturned")
                        .WithMany("Refunded")
                        .HasForeignKey("SaleIdReturned");
                });

            modelBuilder.Entity("Database.Models.SaleModel", b =>
                {
                    b.HasOne("Database.Models.EmployeeModel", "Employee")
                        .WithMany("Sale")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Database.Models.SavedItemModel", b =>
                {
                    b.HasOne("Database.Models.ItemModel", "Item")
                        .WithMany("SavedItems")
                        .HasForeignKey("ItemId");

                    b.HasOne("Database.Models.SavedTransactionModel", "SavedTrans")
                        .WithMany("SavedItems")
                        .HasForeignKey("SavedTransId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.StockModel", b =>
                {
                    b.HasOne("Database.Models.ItemModel", "Item")
                        .WithOne("Stock")
                        .HasForeignKey("Database.Models.StockModel", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.StoreModel", "Store")
                        .WithMany("Stocks")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.TransactionModel", b =>
                {
                    b.HasOne("Database.Models.ItemModel", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.SaleModel", "Sale")
                        .WithMany("Transactions")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
