//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N_L10N.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18N_L10N.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        internal static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add {0}.
        /// </summary>
        internal static string AddArg {
            get {
                return ResourceManager.GetString("AddArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Basket.
        /// </summary>
        internal static string AddToBasket {
            get {
                return ResourceManager.GetString("AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        internal static string Adjust {
            get {
                return ResourceManager.GetString("Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string AdLine1 {
            get {
                return ResourceManager.GetString("AdLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string AdLine2 {
            get {
                return ResourceManager.GetString("AdLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterations.
        /// </summary>
        internal static string Alterations {
            get {
                return ResourceManager.GetString("Alterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter Transaction.
        /// </summary>
        internal static string AltTransaction {
            get {
                return ResourceManager.GetString("AltTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Server Style.
        /// </summary>
        internal static string AppStyle {
            get {
                return ResourceManager.GetString("AppStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Database? 
        ///This will remove all data about your store, items and sales!
        ///The application will need to be restarted after this process..
        /// </summary>
        internal static string AreYouSureDeleteDb {
            get {
                return ResourceManager.GetString("AreYouSureDeleteDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation Required.
        /// </summary>
        internal static string AuthReq {
            get {
                return ResourceManager.GetString("AuthReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        internal static string BackupDb {
            get {
                return ResourceManager.GetString("BackupDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag.
        /// </summary>
        internal static string Bag {
            get {
                return ResourceManager.GetString("Bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskets.
        /// </summary>
        internal static string Baskets {
            get {
                return ResourceManager.GetString("Baskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current basket will be cleared if you continue..
        /// </summary>
        internal static string BasketWillBeClearedMesg {
            get {
                return ResourceManager.GetString("BasketWillBeClearedMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Transaction.
        /// </summary>
        internal static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Charge of {0}.
        /// </summary>
        internal static string CardChargeNote {
            get {
                return ResourceManager.GetString("CardChargeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give {0} as cashback/change..
        /// </summary>
        internal static string CashBack {
            get {
                return ResourceManager.GetString("CashBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Printer.
        /// </summary>
        internal static string ChangePrinter {
            get {
                return ResourceManager.GetString("ChangePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string CheckoutTransaction {
            get {
                return ResourceManager.GetString("CheckoutTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        internal static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfPassword {
            get {
                return ResourceManager.GetString("ConfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost To Store.
        /// </summary>
        internal static string CostToStore {
            get {
                return ResourceManager.GetString("CostToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        internal static string CreateWithArg {
            get {
                return ResourceManager.GetString("CreateWithArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Issue has casued the operatoin to fail, Please try again..
        /// </summary>
        internal static string CriticalIssue {
            get {
                return ResourceManager.GetString("CriticalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Display.
        /// </summary>
        internal static string CurrencyDisplay {
            get {
                return ResourceManager.GetString("CurrencyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Display: {0}.
        /// </summary>
        internal static string CurrencyDisplayArg {
            get {
                return ResourceManager.GetString("CurrencyDisplayArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Data.
        /// </summary>
        internal static string DataArg {
            get {
                return ResourceManager.GetString("DataArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem either accessing a DB value or there was a conflict..
        /// </summary>
        internal static string DbIssue {
            get {
                return ResourceManager.GetString("DbIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Database.
        /// </summary>
        internal static string DeleteDb {
            get {
                return ResourceManager.GetString("DeleteDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find any user with those details
        ///Please try again..
        /// </summary>
        internal static string DetailsNotCorrectORUserNotExistMesg {
            get {
                return ResourceManager.GetString("DetailsNotCorrectORUserNotExistMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Device does not support this operation.
        /// </summary>
        internal static string DeviceNotSupported {
            get {
                return ResourceManager.GetString("DeviceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        internal static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string EmpFormat {
            get {
                return ResourceManager.GetString("EmpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty, {0}.
        /// </summary>
        internal static string EmptyArg {
            get {
                return ResourceManager.GetString("EmptyArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0} here.
        /// </summary>
        internal static string EnterHere {
            get {
                return ResourceManager.GetString("EnterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0} here (Optional).
        /// </summary>
        internal static string EnterHereOptional {
            get {
                return ResourceManager.GetString("EnterHereOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. Tax.
        /// </summary>
        internal static string ExTax {
            get {
                return ResourceManager.GetString("ExTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the following item(s):
        ///
        ///{0}.
        /// </summary>
        internal static string FailedToAddItems {
            get {
                return ResourceManager.GetString("FailedToAddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required.
        /// </summary>
        internal static string FieldRequiredWithArg {
            get {
                return ResourceManager.GetString("FieldRequiredWithArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Lookup.
        /// </summary>
        internal static string FolderLookup {
            get {
                return ResourceManager.GetString("FolderLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Address.
        /// </summary>
        internal static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm....
        /// </summary>
        internal static string Hmm {
            get {
                return ResourceManager.GetString("Hmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much to pay with {0}, There is {1} left to pay.
        /// </summary>
        internal static string HowMuchPM {
            get {
                return ResourceManager.GetString("HowMuchPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much to refund with {0}, There is {1} left to refund.
        /// </summary>
        internal static string HowMuchRefund {
            get {
                return ResourceManager.GetString("HowMuchRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ID.
        /// </summary>
        internal static string IdArg {
            get {
                return ResourceManager.GetString("IdArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc. Tax.
        /// </summary>
        internal static string IncTax {
            get {
                return ResourceManager.GetString("IncTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initalizing {0}....
        /// </summary>
        internal static string InitArg {
            get {
                return ResourceManager.GetString("InitArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Managment.
        /// </summary>
        internal static string InventMgmt {
            get {
                return ResourceManager.GetString("InventMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of items that are trying to be returned exceeds the amount at purchase.
        ///The amount of items at purchase for {0} was {1}, Please remove atleast {2}..
        /// </summary>
        internal static string ItemAmountExceedsMesg {
            get {
                return ResourceManager.GetString("ItemAmountExceedsMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists!.
        /// </summary>
        internal static string ItemExists {
            get {
                return ResourceManager.GetString("ItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item you have scanned doesn&apos;t apear to have been purchased with that Sale ID, Please check and try again..
        /// </summary>
        internal static string ItemNotExistInSaleMesg {
            get {
                return ResourceManager.GetString("ItemNotExistInSaleMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find an item with that ID, Please check and try again..
        /// </summary>
        internal static string ItemNotFoundMesg {
            get {
                return ResourceManager.GetString("ItemNotFoundMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate.
        /// </summary>
        internal static string Locate {
            get {
                return ResourceManager.GetString("Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required information, Please try again..
        /// </summary>
        internal static string MissingRequiredDataMesg {
            get {
                return ResourceManager.GetString("MissingRequiredDataMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNum {
            get {
                return ResourceManager.GetString("MobileNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        ///Please try another name..
        /// </summary>
        internal static string NameMustBeUniqueMesg {
            get {
                return ResourceManager.GetString("NameMustBeUniqueMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Insurance Number.
        /// </summary>
        internal static string NiNo {
            get {
                return ResourceManager.GetString("NiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printer selected will be defaulting to PDF receipts.
        /// </summary>
        internal static string NoPrinter {
            get {
                return ResourceManager.GetString("NoPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are only {0} of {1} left for refunding on this Sale ID..
        /// </summary>
        internal static string NoRefundsLeftMesg {
            get {
                return ResourceManager.GetString("NoRefundsLeftMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stock tracking = -1.
        /// </summary>
        internal static string NoStockTrancking {
            get {
                return ResourceManager.GetString("NoStockTrancking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}s not identicle.
        /// </summary>
        internal static string NotIdenticle {
            get {
                return ResourceManager.GetString("NotIdenticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not valid.
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not valid
        ///{1}.
        /// </summary>
        internal static string NotValidWithRequirements {
            get {
                return ResourceManager.GetString("NotValidWithRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Value or Currency Symbol.
        /// </summary>
        internal static string NumAndCurrencyVal {
            get {
                return ResourceManager.GetString("NumAndCurrencyVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numverical Value.
        /// </summary>
        internal static string NumVal {
            get {
                return ResourceManager.GetString("NumVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        internal static string PassConf {
            get {
                return ResourceManager.GetString("PassConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay full exact amount.
        /// </summary>
        internal static string PayFull {
            get {
                return ResourceManager.GetString("PayFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string PayMeth {
            get {
                return ResourceManager.GetString("PayMeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Permissions.
        /// </summary>
        internal static string PermisionsArg {
            get {
                return ResourceManager.GetString("PermisionsArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a POS device still in an active state, please wait for the device to be finished..
        /// </summary>
        internal static string POSDeviceStillActive {
            get {
                return ResourceManager.GetString("POSDeviceStillActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Ex. Tax.
        /// </summary>
        internal static string PriceExTax {
            get {
                return ResourceManager.GetString("PriceExTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which printer do you use?.
        /// </summary>
        internal static string PrinterList {
            get {
                return ResourceManager.GetString("PrinterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qty.
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover local database.
        /// </summary>
        internal static string RecoverDB {
            get {
                return ResourceManager.GetString("RecoverDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string RecoveryTitle {
            get {
                return ResourceManager.GetString("RecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunds.
        /// </summary>
        internal static string Refunds {
            get {
                return ResourceManager.GetString("Refunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        internal static string RemoveArg {
            get {
                return ResourceManager.GetString("RemoveArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        internal static string RestoreDb {
            get {
                return ResourceManager.GetString("RestoreDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving {0}....
        /// </summary>
        internal static string RetrievingArg {
            get {
                return ResourceManager.GetString("RetrievingArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Unwanted, faulty, etc..
        /// </summary>
        internal static string ReturnReasonExample {
            get {
                return ResourceManager.GetString("ReturnReasonExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        internal static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert {0}.
        /// </summary>
        internal static string RevertArg {
            get {
                return ResourceManager.GetString("RevertArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Abbrevation.
        /// </summary>
        internal static string SAbbr {
            get {
                return ResourceManager.GetString("SAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Ex. Tax.
        /// </summary>
        internal static string SaleExTax {
            get {
                return ResourceManager.GetString("SaleExTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Sale ID is does not exist, Please check and retry..
        /// </summary>
        internal static string SaleIDWrongMesg {
            get {
                return ResourceManager.GetString("SaleIDWrongMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Inc. Tax.
        /// </summary>
        internal static string SaleIncTax {
            get {
                return ResourceManager.GetString("SaleIncTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Reports.
        /// </summary>
        internal static string SalesReports {
            get {
                return ResourceManager.GetString("SalesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0}....
        /// </summary>
        internal static string SearchArg {
            get {
                return ResourceManager.GetString("SearchArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Style.
        /// </summary>
        internal static string ServerStyle {
            get {
                return ResourceManager.GetString("ServerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Up.
        /// </summary>
        internal static string SetUpTitle {
            get {
                return ResourceManager.GetString("SetUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string SName {
            get {
                return ResourceManager.GetString("SName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of Week.
        /// </summary>
        internal static string StartOfWeek {
            get {
                return ResourceManager.GetString("StartOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of Week: {0}.
        /// </summary>
        internal static string StartOfWeekArg {
            get {
                return ResourceManager.GetString("StartOfWeekArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Outtake Report.
        /// </summary>
        internal static string StockOuttakeReport {
            get {
                return ResourceManager.GetString("StockOuttakeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Information.
        /// </summary>
        internal static string StoreInformation {
            get {
                return ResourceManager.GetString("StoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Transaction.
        /// </summary>
        internal static string StoreTransaction {
            get {
                return ResourceManager.GetString("StoreTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string TaxName {
            get {
                return ResourceManager.GetString("TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name for {0}%.
        /// </summary>
        internal static string TaxNameArg {
            get {
                return ResourceManager.GetString("TaxNameArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for shopping at.
        /// </summary>
        internal static string ThankYouShopping {
            get {
                return ResourceManager.GetString("ThankYouShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        internal static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} To Increment/Decrement.
        /// </summary>
        internal static string ToIncrement_Decrement {
            get {
                return ResourceManager.GetString("ToIncrement/Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Transfer.
        /// </summary>
        internal static string TPT {
            get {
                return ResourceManager.GetString("TPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost of this Transaction is {0}
        ///Are you sure you wish to continue?.
        /// </summary>
        internal static string TransacContinue {
            get {
                return ResourceManager.GetString("TransacContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Name.
        /// </summary>
        internal static string TransactionName {
            get {
                return ResourceManager.GetString("TransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed, transaction complete.
        /// </summary>
        internal static string TransConfMesg {
            get {
                return ResourceManager.GetString("TransConfMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        internal static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Stock.
        /// </summary>
        internal static string UpdateStock {
            get {
                return ResourceManager.GetString("UpdateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All {0}.
        /// </summary>
        internal static string ViewAllArg {
            get {
                return ResourceManager.GetString("ViewAllArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait!.
        /// </summary>
        internal static string Wait_ {
            get {
                return ResourceManager.GetString("Wait!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
