//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N_L10N.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18N_L10N.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        internal static string ActivUsers {
            get {
                return ResourceManager.GetString("ActivUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Description.
        /// </summary>
        internal static string AddDesc {
            get {
                return ResourceManager.GetString("AddDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string AddEmp {
            get {
                return ResourceManager.GetString("AddEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string AdLine1 {
            get {
                return ResourceManager.GetString("AdLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string AdLine2 {
            get {
                return ResourceManager.GetString("AdLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not Authorized to access this..
        /// </summary>
        internal static string AuthDeniedMesg {
            get {
                return ResourceManager.GetString("AuthDeniedMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUp DB.
        /// </summary>
        internal static string BackUp {
            get {
                return ResourceManager.GetString("BackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basket is empty, Please add items and try again.
        /// </summary>
        internal static string BasketEmpty {
            get {
                return ResourceManager.GetString("BasketEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace current basket?
        ///If you do the current basket will be lost..
        /// </summary>
        internal static string BasketReplace {
            get {
                return ResourceManager.GetString("BasketReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskets.
        /// </summary>
        internal static string Baskets {
            get {
                return ResourceManager.GetString("Baskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Address.
        /// </summary>
        internal static string ButtAddressAuto {
            get {
                return ResourceManager.GetString("ButtAddressAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Address.
        /// </summary>
        internal static string ButtAddressMan {
            get {
                return ResourceManager.GetString("ButtAddressMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take/Select Image.
        /// </summary>
        internal static string ButtImage {
            get {
                return ResourceManager.GetString("ButtImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this transaction?.
        /// </summary>
        internal static string CancelTransaction_Mesg {
            get {
                return ResourceManager.GetString("CancelTransaction_Mesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Charge of {0}.
        /// </summary>
        internal static string CardChargeNote {
            get {
                return ResourceManager.GetString("CardChargeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Cate {
            get {
                return ResourceManager.GetString("Cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNoCharge.
        /// </summary>
        internal static string CNoC {
            get {
                return ResourceManager.GetString("CNoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost of this Transaction is £{0}
        ///Are you sure you wish to continue?.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracted Weekly Hours.
        /// </summary>
        internal static string ContrHours {
            get {
                return ResourceManager.GetString("ContrHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string COut {
            get {
                return ResourceManager.GetString("COut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Create New Category&apos;.
        /// </summary>
        internal static string CreateNCate {
            get {
                return ResourceManager.GetString("CreateNCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stock.
        /// </summary>
        internal static string CStock {
            get {
                return ResourceManager.GetString("CStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no stock exist input &apos;0&apos;.
        /// </summary>
        internal static string CStockPL {
            get {
                return ResourceManager.GetString("CStockPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a type of Database.
        /// </summary>
        internal static string DatabaseNotSelectedMesg {
            get {
                return ResourceManager.GetString("DatabaseNotSelectedMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        internal static string DatabaseType {
            get {
                return ResourceManager.GetString("DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem {0} the database..
        /// </summary>
        internal static string DbBRFailed {
            get {
                return ResourceManager.GetString("DbBRFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database has been {0} successfully..
        /// </summary>
        internal static string DbBRSucc {
            get {
                return ResourceManager.GetString("DbBRSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem either accessing a DB value or there was a conflict..
        /// </summary>
        internal static string DbIssue {
            get {
                return ResourceManager.GetString("DbIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot deactivate the current user authorising deactivation.
        /// </summary>
        internal static string DeactAuthUser {
            get {
                return ResourceManager.GetString("DeactAuthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to DEACTIVATE {0}, profile?.
        /// </summary>
        internal static string Deactiv_Mesg {
            get {
                return ResourceManager.GetString("Deactiv_Mesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find any user with those details
        ///Please try again..
        /// </summary>
        internal static string DetailsNotCorrectORUserNotExistMesg {
            get {
                return ResourceManager.GetString("DetailsNotCorrectORUserNotExistMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Ensure your E-Mail is valid and correct.
        /// </summary>
        internal static string EmailNotCorrectMesg {
            get {
                return ResourceManager.GetString("EmailNotCorrectMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Deactivation for {0} was successful.
        /// </summary>
        internal static string EmpDeactSuc {
            get {
                return ResourceManager.GetString("EmpDeactSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string EmpId {
            get {
                return ResourceManager.GetString("EmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the employee ID or Date of Sales you want to look up.
        /// </summary>
        internal static string EmpIdORDate {
            get {
                return ResourceManager.GetString("EmpIdORDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        internal static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section is for the employee to fill out..
        /// </summary>
        internal static string EmployeeSecMesg {
            get {
                return ResourceManager.GetString("EmployeeSecMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee Id you have inputted is currently not logged in.
        /// </summary>
        internal static string EmpNotLogged {
            get {
                return ResourceManager.GetString("EmpNotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Emps {
            get {
                return ResourceManager.GetString("Emps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Ensure all required fields are filled in.
        /// </summary>
        internal static string FieldsFilledInMesg {
            get {
                return ResourceManager.GetString("FieldsFilledInMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Address.
        /// </summary>
        internal static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Plutus POS.
        /// </summary>
        internal static string FWelcomeTitle {
            get {
                return ResourceManager.GetString("FWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm....
        /// </summary>
        internal static string Hmm {
            get {
                return ResourceManager.GetString("Hmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID/Name.
        /// </summary>
        internal static string IDName {
            get {
                return ResourceManager.GetString("IDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As this is the first time your using the Plutus POS System, you will have to create a new account..
        /// </summary>
        internal static string IntroL1 {
            get {
                return ResourceManager.GetString("IntroL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already have a cloud/local system, then please switch to the store login page..
        /// </summary>
        internal static string IntroL2 {
            get {
                return ResourceManager.GetString("IntroL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string InvetMgr {
            get {
                return ResourceManager.GetString("InvetMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of items that are trying to be returned exceeds the amount at purchase.
        ///The amount of items at purchase for {0} was {1}, Please remove atleast {2}..
        /// </summary>
        internal static string ItemAmountExceedsMesg {
            get {
                return ResourceManager.GetString("ItemAmountExceedsMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item apears to already been added.
        ///Please check this..
        /// </summary>
        internal static string ItemExistMesg {
            get {
                return ResourceManager.GetString("ItemExistMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a item with that ID.
        /// </summary>
        internal static string ItemIdNotFoundMesg {
            get {
                return ResourceManager.GetString("ItemIdNotFoundMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item does not apear to have been added.
        ///Please check this..
        /// </summary>
        internal static string ItemNonExistMesg {
            get {
                return ResourceManager.GetString("ItemNonExistMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item you have scanned doesn&apos;t apear to have been purchased with that Sale ID, Please check and try again..
        /// </summary>
        internal static string ItemNotExistInSaleMesg {
            get {
                return ResourceManager.GetString("ItemNotExistInSaleMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a item with that ID or Name.
        /// </summary>
        internal static string ItemNotFoundMesg {
            get {
                return ResourceManager.GetString("ItemNotFoundMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout All.
        /// </summary>
        internal static string LogoutAll {
            get {
                return ResourceManager.GetString("LogoutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        internal static string NewCate {
            get {
                return ResourceManager.GetString("NewCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Inventory Item.
        /// </summary>
        internal static string NewInvetItem {
            get {
                return ResourceManager.GetString("NewInvetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Login.
        /// </summary>
        internal static string NewUserLogin {
            get {
                return ResourceManager.GetString("NewUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Insurance Number.
        /// </summary>
        internal static string Nin {
            get {
                return ResourceManager.GetString("Nin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no active users.
        /// </summary>
        internal static string NoActiveUsers {
            get {
                return ResourceManager.GetString("NoActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made no change to any of the objects values
        ///Please change something or go back.
        /// </summary>
        internal static string NoChangeMadeMesg {
            get {
                return ResourceManager.GetString("NoChangeMadeMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All amounts of {0} for this Sale ID have been returned already..
        /// </summary>
        internal static string NoRefundsLeftMesg {
            get {
                return ResourceManager.GetString("NoRefundsLeftMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Section.
        /// </summary>
        internal static string OfficeSec {
            get {
                return ResourceManager.GetString("OfficeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For office use only..
        /// </summary>
        internal static string OfficeSecMesg {
            get {
                return ResourceManager.GetString("OfficeSecMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS.
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners Address.
        /// </summary>
        internal static string OwnerAddress {
            get {
                return ResourceManager.GetString("OwnerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print receipt?.
        /// </summary>
        internal static string PaperReceipt {
            get {
                return ResourceManager.GetString("PaperReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PassW {
            get {
                return ResourceManager.GetString("PassW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        internal static string PassWConf {
            get {
                return ResourceManager.GetString("PassWConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not the same
        ///OR
        ///Not longer than 6 characters
        ///Please try again.
        /// </summary>
        internal static string PassWNotSameMesg {
            get {
                return ResourceManager.GetString("PassWNotSameMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method Selection.
        /// </summary>
        internal static string PayMeth {
            get {
                return ResourceManager.GetString("PayMeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Ensure your Post Code is valid and correct.
        /// </summary>
        internal static string PCNotCorrectMesg {
            get {
                return ResourceManager.GetString("PCNotCorrectMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneN {
            get {
                return ResourceManager.GetString("PhoneN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Ensure your Phone Number is valid and correct.
        /// </summary>
        internal static string PhoneNumNotCorrectMesg {
            get {
                return ResourceManager.GetString("PhoneNumNotCorrectMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Roll.
        /// </summary>
        internal static string PRoll {
            get {
                return ResourceManager.GetString("PRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to Add.
        /// </summary>
        internal static string QuantityAdd {
            get {
                return ResourceManager.GetString("QuantityAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit Plutus POS?.
        /// </summary>
        internal static string Quit_Mesg {
            get {
                return ResourceManager.GetString("Quit_Mesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove 1.
        /// </summary>
        internal static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomended Price.
        /// </summary>
        internal static string RecPrice {
            get {
                return ResourceManager.GetString("RecPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please get a manager OR other employee with higher returns rights to authorise this transaction.
        /// </summary>
        internal static string RefundLimitTooLow {
            get {
                return ResourceManager.GetString("RefundLimitTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        internal static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights and Restrictions.
        /// </summary>
        internal static string Ri_Re {
            get {
                return ResourceManager.GetString("Ri_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Ex.VAT.
        /// </summary>
        internal static string SaleExV {
            get {
                return ResourceManager.GetString("SaleExV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale ID.
        /// </summary>
        internal static string SaleID {
            get {
                return ResourceManager.GetString("SaleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Sale ID is does not exist, Please check and retry..
        /// </summary>
        internal static string SaleIDWrongMesg {
            get {
                return ResourceManager.GetString("SaleIDWrongMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Address.
        /// </summary>
        internal static string SameAd {
            get {
                return ResourceManager.GetString("SameAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Basket.
        /// </summary>
        internal static string SaveB {
            get {
                return ResourceManager.GetString("SaveB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your cloud data service.
        /// </summary>
        internal static string SelectCloudService {
            get {
                return ResourceManager.GetString("SelectCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set your password.
        /// </summary>
        internal static string SetPassWMesg {
            get {
                return ResourceManager.GetString("SetPassWMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string SomthingWentWrongMesg {
            get {
                return ResourceManager.GetString("SomthingWentWrongMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Reports.
        /// </summary>
        internal static string SReports {
            get {
                return ResourceManager.GetString("SReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string SResults {
            get {
                return ResourceManager.GetString("SResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name Abbreviation (4 letters).
        /// </summary>
        internal static string StAbbr {
            get {
                return ResourceManager.GetString("StAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Address.
        /// </summary>
        internal static string StAddress {
            get {
                return ResourceManager.GetString("StAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Deactivation.
        /// </summary>
        internal static string StaffDeactiv {
            get {
                return ResourceManager.GetString("StaffDeactiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Management.
        /// </summary>
        internal static string StaffMgnt {
            get {
                return ResourceManager.GetString("StaffMgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Details.
        /// </summary>
        internal static string StDetails {
            get {
                return ResourceManager.GetString("StDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Update.
        /// </summary>
        internal static string StockUpdate {
            get {
                return ResourceManager.GetString("StockUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a problem on our end, please check the database for corruption..
        /// </summary>
        internal static string StoreNotReachableMesg {
            get {
                return ResourceManager.GetString("StoreNotReachableMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Owner Details.
        /// </summary>
        internal static string StOwnerDetails {
            get {
                return ResourceManager.GetString("StOwnerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax %.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        internal static string TaxType {
            get {
                return ResourceManager.GetString("TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        internal static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed transaction complete.
        /// </summary>
        internal static string TransConfMesg {
            get {
                return ResourceManager.GetString("TransConfMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Item.
        /// </summary>
        internal static string UpdateItem {
            get {
                return ResourceManager.GetString("UpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Items.
        /// </summary>
        internal static string VAllItems {
            get {
                return ResourceManager.GetString("VAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value you enter was not correct, Please input in the format asked.
        /// </summary>
        internal static string ValueEnteredWrong {
            get {
                return ResourceManager.GetString("ValueEnteredWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Per Hour.
        /// </summary>
        internal static string Wage {
            get {
                return ResourceManager.GetString("Wage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
