// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plutus.Entities;

#nullable disable

namespace Plutus.Entities.Migrations.MySql
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260724224309_AddAdminAudit")]
    partial class AddAdminAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Plutus.Entities.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "AtUtc");

                    b.HasIndex("TenantId", "EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActionAPIMapping", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.ToTable("AuthActionAPIMapping");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuthActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameAbbr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("RecMarkup")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VatIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.Property<Guid>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.HasIndex("TenantId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ExPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("CheckoutItemChange");
                });

            modelBuilder.Entity("Plutus.Entities.Models.ConsumerDeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("OutboxId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerName");

                    b.ToTable("ConsumerDeadLetters", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.ConsumerOffset", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("LastOutboxId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ConsumerName");

                    b.ToTable("ConsumerOffsets", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LastSeenSeq")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("SecretSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TillId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TillId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllApplicable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("AutoApply")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanUseWithOtherDiscounts")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("RequiredNumOfItems")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UsesPerTransaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("TenantId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CatIdOne")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CatIdTwo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CatIdOne", "CatIdTwo");

                    b.ToTable("DiscountCats");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("DiscountItems");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Emp_AuthActions", b =>
                {
                    b.Property<int>("AuthAId")
                        .HasColumnType("int");

                    b.Property<Guid>("EmpId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.HasKey("AuthAId", "EmpId");

                    b.HasIndex("EmpId");

                    b.ToTable("EmpAuthActions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.EnrolmentCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TillId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("TillId");

                    b.ToTable("EnrolmentCodes", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CatId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ExPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TaxId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.HasIndex("TenantId");

                    b.HasIndex("CatId", "IdTwo");

                    b.HasIndex("TaxId", "IdTwo");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Note", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOne"));

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.HasIndex("TenantId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.OutboxEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCashBackable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsChangeable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MinimumCharge")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PayMethods");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod_Sale", b =>
                {
                    b.Property<int>("PayId")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("PayId", "SaleId");

                    b.HasIndex("SaleId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaySales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdLine1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdLine2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("People");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Plutus.Entities.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ConsumerName", "EventId");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.RbacRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("RbacRoles", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.RbacRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<byte?>("DaysOfWeekMask")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<byte>("ScopeType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeOnly?>("WindowEndLocal")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly?>("WindowStartLocal")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("TenantId", "ScopeType", "ScopeId");

                    b.ToTable("RbacRoleAssignments", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.RbacRoleGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<long?>("MaxPence")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("RoleId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("RbacRoleGrants", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("AuthoriserId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("CheckoutItemChangeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SaleIdReturned")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AuthoriserId");

                    b.HasIndex("CheckoutItemChangeId")
                        .IsUnique();

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleIdReturned");

                    b.HasIndex("TenantId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ParentRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DateOfSale"));

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TillId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalExTax")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TillId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AdjustmentSaleId")
                        .HasColumnType("char(36)");

                    b.Property<long>("AmountPence")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AuthoriserUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OriginalSaleId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OriginalSaleId");

                    b.ToTable("SaleAdjustments", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<long>("DiscountPence")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscountsJson")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<long>("LineGrossPence")
                        .HasColumnType("bigint");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<long?>("OverriddenFromPence")
                        .HasColumnType("bigint");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<long>("UnitPricePence")
                        .HasColumnType("bigint");

                    b.Property<long>("VatAmountPence")
                        .HasColumnType("bigint");

                    b.Property<int>("VatRateBp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ItemId");

                    b.HasIndex("TenantId", "SaleId");

                    b.ToTable("SaleLines", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleQuarantine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SaleId")
                        .IsUnique();

                    b.ToTable("SaleQuarantine", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleTender", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<long>("AmountPence")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangePence")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("TenderType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SaleId");

                    b.ToTable("SaleTenders", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleV2", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("BusinessDay")
                        .HasColumnType("date");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<long>("DeviceSeq")
                        .HasColumnType("bigint");

                    b.Property<long>("GrossPence")
                        .HasColumnType("bigint");

                    b.Property<string>("LegacyRef")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TillId")
                        .HasColumnType("char(36)");

                    b.Property<long>("VatPence")
                        .HasColumnType("bigint");

                    b.Property<bool>("VatReconstructed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "BusinessDay");

                    b.HasIndex("TenantId", "DeviceId", "DeviceSeq")
                        .IsUnique();

                    b.HasIndex("TenantId", "TillId", "BusinessDay");

                    b.ToTable("SalesV2", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.SavedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("SavedTransactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Stock", b =>
                {
                    b.Property<string>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("IdThree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdOne", "IdTwo", "IdThree");

                    b.HasIndex("IdThree");

                    b.HasIndex("TenantId");

                    b.HasIndex("IdOne", "IdTwo")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdLine1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdLine2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("TenantId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Plutus.Entities.Models.StoreDetails", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("OpeningHoursJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("StoreId");

                    b.HasIndex("TenantId");

                    b.ToTable("StoreDetails", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOne"));

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("IdTwo");

                    b.HasIndex("TenantId");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConnectionRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entitlements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CashFloat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.ToTable("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.Property<int>("IdOne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOne"));

                    b.Property<Guid>("IdTwo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CheckoutItemChangeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ItemCostExPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ItemCostPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ItemIdOne")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ItemIdTwo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TillId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdOne", "IdTwo");

                    b.HasIndex("CheckoutItemChangeId")
                        .IsUnique();

                    b.HasIndex("IdTwo");

                    b.HasIndex("TenantId");

                    b.HasIndex("TillId");

                    b.HasIndex("ItemIdOne", "ItemIdTwo");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction_Discount", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("TransactionId", "DiscountId", "SaleId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionId", "SaleId");

                    b.ToTable("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.WebCredential", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Email");

                    b.ToTable("WebCredentials", (string)null);
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.HasBaseType("Plutus.Entities.Models.Person");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ContractedHours")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("NIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(65,30)");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("StoreId");

                    b.HasIndex("Id", "BusinessId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActionAPIMapping", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Role", "Role")
                        .WithMany("AuthActionAPIMappings")
                        .HasForeignKey("IdOne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.AuthActions", "AuthAction")
                        .WithMany("AuthActionAPIMappings")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Categories")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("CheckoutItemChanges")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Discounts")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Category", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("DisCategoryList")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Category", "Cat")
                        .WithMany("Discount_Categories")
                        .HasForeignKey("CatIdOne", "CatIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount_Item", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("DisItemList")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("DisItems")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Emp_AuthActions", b =>
                {
                    b.HasOne("Plutus.Entities.Models.AuthActions", "AuthA")
                        .WithMany("EmpAuths")
                        .HasForeignKey("AuthAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Employee", "Emp")
                        .WithMany("EmpAuths")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthA");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Items")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Category", "Cat")
                        .WithMany("Items")
                        .HasForeignKey("CatId", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Tax", "Tax")
                        .WithMany("Items")
                        .HasForeignKey("TaxId", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Cat");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Note", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Notes")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod_Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.PaymentMethod", "PayMethod")
                        .WithMany("PaySales")
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("PaySales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayMethod");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Plutus.Entities.Models.RbacRoleAssignment", b =>
                {
                    b.HasOne("Plutus.Entities.Models.RbacRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Plutus.Entities.Models.RbacRoleGrant", b =>
                {
                    b.HasOne("Plutus.Entities.Models.RbacRole", null)
                        .WithMany("Grants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plutus.Entities.Models.Refund", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Employee", "Authoriser")
                        .WithMany("RefundsAuthorised")
                        .HasForeignKey("AuthoriserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.CheckoutItemChange", "CheckoutItemChange")
                        .WithOne("Refund")
                        .HasForeignKey("Plutus.Entities.Models.Refund", "CheckoutItemChangeId");

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Refunds")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Sale", "SaleReturned")
                        .WithMany("Refunded")
                        .HasForeignKey("SaleIdReturned")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("Refunds")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authoriser");

                    b.Navigation("CheckoutItemChange");

                    b.Navigation("Item");

                    b.Navigation("Sale");

                    b.Navigation("SaleReturned");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Roles")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Role", "ParentRole")
                        .WithMany()
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Employee", "Employee")
                        .WithMany("Sale")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Till", "Till")
                        .WithMany()
                        .HasForeignKey("TillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Store");

                    b.Navigation("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleLine", b =>
                {
                    b.HasOne("Plutus.Entities.Models.SaleV2", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleTender", b =>
                {
                    b.HasOne("Plutus.Entities.Models.SaleV2", null)
                        .WithMany("Tenders")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plutus.Entities.Models.Stock", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Stocks")
                        .HasForeignKey("IdThree")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithOne("Stock")
                        .HasForeignKey("Plutus.Entities.Models.Stock", "IdOne", "IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Stores")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Taxes")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Tills")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.HasOne("Plutus.Entities.Models.CheckoutItemChange", "CheckoutItemChange")
                        .WithOne("Transaction")
                        .HasForeignKey("Plutus.Entities.Models.Transaction", "CheckoutItemChangeId");

                    b.HasOne("Plutus.Entities.Models.Sale", "Sale")
                        .WithMany("Transactions")
                        .HasForeignKey("IdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Till", "Till")
                        .WithMany("Transactions")
                        .HasForeignKey("TillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemIdOne", "ItemIdTwo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckoutItemChange");

                    b.Navigation("Item");

                    b.Navigation("Sale");

                    b.Navigation("Till");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction_Discount", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Discount", "Discount")
                        .WithMany("Transaction_Discounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Transaction", "Transaction")
                        .WithMany("Transaction_Discounts")
                        .HasForeignKey("TransactionId", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.HasOne("Plutus.Entities.Models.Business", "Business")
                        .WithMany("Employees")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Plutus.Entities.Models.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Entities.Models.Employee", "ManagedBy")
                        .WithMany()
                        .HasForeignKey("ManagedById");

                    b.HasOne("Plutus.Entities.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId");

                    b.HasOne("Plutus.Entities.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("ManagedBy");

                    b.Navigation("Role");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Plutus.Entities.Models.AuthActions", b =>
                {
                    b.Navigation("AuthActionAPIMappings");

                    b.Navigation("EmpAuths");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Business", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Discounts");

                    b.Navigation("Employees");

                    b.Navigation("Items");

                    b.Navigation("Roles");

                    b.Navigation("Stores");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Category", b =>
                {
                    b.Navigation("Discount_Categories");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.CheckoutItemChange", b =>
                {
                    b.Navigation("Refund")
                        .IsRequired();

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("Plutus.Entities.Models.Discount", b =>
                {
                    b.Navigation("DisCategoryList");

                    b.Navigation("DisItemList");

                    b.Navigation("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Item", b =>
                {
                    b.Navigation("CheckoutItemChanges");

                    b.Navigation("DisItems");

                    b.Navigation("Refunds");

                    b.Navigation("Stock");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.PaymentMethod", b =>
                {
                    b.Navigation("PaySales");
                });

            modelBuilder.Entity("Plutus.Entities.Models.RbacRole", b =>
                {
                    b.Navigation("Grants");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Role", b =>
                {
                    b.Navigation("AuthActionAPIMappings");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Sale", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PaySales");

                    b.Navigation("Refunded");

                    b.Navigation("Refunds");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.SaleV2", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Sales");

                    b.Navigation("Stocks");

                    b.Navigation("Tills");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Tax", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Till", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Transaction", b =>
                {
                    b.Navigation("Transaction_Discounts");
                });

            modelBuilder.Entity("Plutus.Entities.Models.Employee", b =>
                {
                    b.Navigation("EmpAuths");

                    b.Navigation("RefundsAuthorised");

                    b.Navigation("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
