<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="2.0.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="2.0.0" />
    <PackageReference Include="Microsoft.AppCenter.Distribute" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.4" />
    <PackageReference Include="Rg.Plugins.Popup" Version="1.1.5.188" />
    <PackageReference Include="SkiaSharp.Extended" Version="1.60.0" />
    <PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
    <PackageReference Include="SkiaSharp.Views" Version="1.68.0" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="1.68.0" />
    <PackageReference Include="Syncfusion.Xamarin.SfCalendar" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.SfChart" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.SfListView" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.SfNumericUpDown" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.SfPicker" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.SfPopupLayout" Version="17.2.0.39" />
    <PackageReference Include="Syncfusion.Xamarin.SfSunburstChart" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.XlsIO" Version="17.2.0.34" />
    <PackageReference Include="Syncfusion.Xamarin.XlsIORenderer" Version="16.4.0.52" />
    <PackageReference Include="Xam.Plugin.Iconize" Version="3.5.0.129" />
    <PackageReference Include="Xam.Plugin.Iconize.FontAwesome" Version="3.5.0.129" />
    <PackageReference Include="Xam.Plugin.Iconize.Material" Version="3.5.0.129" />
    <PackageReference Include="Xam.Plugins.Settings" Version="3.1.1" />
    <PackageReference Include="Xamarin.Essentials" Version="1.2.0" />
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.618606" />
    <PackageReference Include="Xamarin.Plugin.FilePicker" Version="2.1.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CustomViews\CustomViews.csproj" />
    <ProjectReference Include="..\..\Database\Database.csproj" />
    <ProjectReference Include="..\..\I18N_L10N\I18N_L10N.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\FirstTimeStartUp\SetupView.xaml.cs">
      <DependentUpon>SetupView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MainTill\Inventory\Items\ViewAllView.xaml.cs">
      <DependentUpon>ViewAllView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MainTill\Statistics\StockOuttakeView.xaml.cs">
      <DependentUpon>StockOuttakeView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MainTill\StoreOptions\StoreOptionsView.xaml.cs">
      <DependentUpon>StoreOptionsView.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Controls\SteppedSliderWithLabels.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CustomViews\SliderAlert.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FirstTimeStartUp\FTSUMainView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FirstTimeStartUp\RecoveryView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FirstTimeStartUp\SetupView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\FirstTimeStartUp\TransferThirdPartyView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LoadingIndicatorView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LoginView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Inventory\InventoryView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Inventory\Items\AddEditView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Inventory\Items\ViewAllView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\MainView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\StoreOptions\StoreOptionsView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Statistics\SalesReportsView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Settings\SettingsView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Statistics\StatisticsView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Statistics\StockOuttakeView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainTill\Till\TillView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Effects\" />
    <Folder Include="Helpers\Enums\" />
    <Folder Include="Resources\" />
  </ItemGroup>
</Project>